<?xml version="1.0" encoding="utf-8"?><Database Name="JDCars" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-2LGR7JU8;Initial Catalog=JDCars;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="JDCarsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CarMake" Member="CarMakes">
    <Type Name="CarMake">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CarMake" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="City_Car" Member="City1" ThisKey="City" OtherKey="City1" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="City" Member="City1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="City_Car" Member="Cars" ThisKey="City1" OtherKey="City" Type="Car" />
    </Type>
  </Table>
  <Function Name="dbo.AddCarEntry" Method="AddCarEntry">
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Province" Parameter="province" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CarMake" Parameter="carMake" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Model" Parameter="model" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchCar" Method="SearchCar">
    <Parameter Name="Manufacturer" Parameter="manufacturer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Model" Parameter="model" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="PriceMin" Parameter="priceMin" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="PriceMax" Parameter="priceMax" Type="System.Decimal" DbType="Decimal(18,2)" />
    <ElementType Name="SearchCarResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CarMake" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectMakerModels" Method="SelectMakerModels">
    <Parameter Name="Maker" Parameter="maker" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SelectMakerModelsResult">
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectModels" Method="SelectModels">
    <ElementType Name="SelectModelsResult">
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectYearModels" Method="SelectYearModels">
    <Parameter Name="YearMax" Parameter="yearMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="YearMin" Parameter="yearMin" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectYearModelsResult">
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>